# signup:
    # resource: "@AmenophisWHMCSBundle/Controller/SignupController.php"
    # type:     annotation
    
amenophis_whmcs_signup:
  pattern: "/signup"
  defaults: { _controller: AmenophisWHMCSBundle:Signup:index }
  requirements:
    _method: GET
      
amenophis_whmcs_signup_process:
  pattern: "/signup/process"
  defaults: { _controller: AmenophisWHMCSBundle:Signup:indexProcess }
  requirements:
    _method: POST

amenophis_whmcs_signup_success:
  pattern: "/signup/complete"
  defaults: { _controller: AmenophisWHMCSBundle:Signup:complete }
  requirements:
    _method: GET