amenophis_whmcs_secured:
  pattern: /secured
  defaults: { _controller: AmenophisWHMCSBundle:Secured:index }

amenophis_whmcs_security:
  pattern: /security
  defaults: { _controller: AmenophisWHMCSBundle:Security:index }
  
amenophis_whmcs_security_signout:
  pattern: /security/signout
  defaults: { _controller: AmenophisWHMCSBundle:Security:signout }

amenophis_whmcs_security_check:
  pattern: /security/check
  defaults: { _controller: AmenophisWHMCSBundle:Security:check }
