parameters:
  amenophis.whmcs.host:        ""
  amenophis.whmcs.username:    ""
  amenophis.whmcs.password:    ""
  amenophis.whmcs.connector:   "FP\WHMCS\Adapter\Json\Connector"
  amenophis.whmcs.user.provider.class: FP\Bundle\WHMCSBundle\Security\UserProvider

services:
  amenophis.whmcs:
    class: %amenophis.whmcs.connector%
    arguments: [%amenophis.whmcs.host%, %amenophis.whmcs.username%, %amenophis.whmcs.password%]
  amenophis.whmcs.user.provider:
    class: %amenophis.whmcs.user.provider.class%
    arguments: [@amenophis.whmcs]
  amenophis.whmcs.encoder:
    class: Amenophis\Bundle\WHMCSBundle\Security\Encoder\WHMCS